--- #YAML:1.0
name:               AnyEvent-Feed
version:            0.2
abstract:           Receiving RSS/Atom Feed reader with XML::Feed
author:
    - Robin Redeker <elmex@x-paste.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:        3.5
    AnyEvent::HTTP:  0
    Digest::SHA1:    0
    Encode:          0
    MIME::Base64:    0
    Scalar::Util:    0
    Test::More:      0
    XML::Feed:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
